/**
 * The menu-bar mark, base64, generated by `npm run icons`.
 *
 * **Do not edit.** Change `icons/top_bar.svg` and run the script.
 *
 * Here rather than on disk because a `Tray` needs an image at runtime and a
 * path that works in `npm run dev` is not the path that works inside a
 * packaged .app. Two kilobytes bundled with the rest of main has no such
 * failure mode.
 *
 * Two sizes because the menu bar draws at 22pt and Retina wants 44px for it.
 * Both are drawn as black-on-transparent and used as **template** images, which
 * is what lets macOS tint them for light mode, dark mode and the highlighted
 * state without Mull knowing which one it is in.
 */
export const TRAY_ICON_1X = 'iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAABLUlEQVR4nOyTza4BQRCFy7judX9yrURsJRYS7yA2HkriDSw8gZfwDMKSlYTYWYpIJP7NOEXV6HRmEDFWTvJFulWdrq6pdigiORSRIjOOW+sYPa5Y6OKZMluRBjl6XJyb0cWH/HLlRbAFWdC+z+uU54GyrNdgCg7a45TQAd8gDyZy8A/4F/5Aks43ZcMDKIE56ErMhtGKv6RarmAICqACVmAnwTvjlp8gAX7BDPQkdyv/+63YG1VwwACMJfCaEnKgtoQ9XO0RyQZfcRmQHDY5XsBeUopxdSpcMVWTJmgYxp6FxlVByzBei5ffCls9ulTvGQeQYc4ahXm85IHY+451eA3UrT2OiQcZhLXCtdb89ft0nmkdzaA4X/e2gueVR5IfBD+gxa2El/f4bfw8HQEAAP//rFBOlQAAAAZJREFUAwCplDuDNBgQbwAAAABJRU5ErkJggg=='

export const TRAY_ICON_2X = 'iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAYAAAAehFoBAAAC9klEQVR4nOyYy49MQRTGv9ttBoOJeIawsLDBQiISbCQ2EiHYiH/AxsJjI5YWEokEIbGRWIjE/yFYWHhLCBkkiDcxHpPR09O+kzo1XVN9b8/tuVVMT+6X/NL31q2qc+6pU4/bFXSZKugylQ7HVulwbJUOx1bXOTwjo9y+yCj+jzLtJ5hYUqeBf6MJbVVTGoj2kg1kgNRg3ji209ZGL9lP1pLHaZVcSYPVWvk7OUE2wwxNzHyvqI2N5AIZIfPJOn0+lglVr5E4vJvcItfJbbKPLCJPECfS1tldZA85qXbfk03koWvXjZpN8MXkuT4bJKfIKrIDzUgn+ltBZ5F32yWOs9vJVnJEHZXyd2Sm1hubfP4q0asVBj0j58hx8pY80HI/0rNJH5lFerRMhnZI+a1t3HZyLekn0T2s966Df8gc8jPL4T41Aq9T6eQ8OebUW04WkLnajxipOTS0vEd/pY86+UW+wURSAnMQZq7U0Vwl7O+wBiDTYdsp0LrESJSuwOT0a/IBJq8/w0zQYbSXON5PFpKlZBnZQi6Tj2imh2tbfBm3kvkOj6DppD90olfkNLKVoHVtt2kgUf+iPEtpO+q1sf3V0MZhyTMZ7grSdzk7UVxHGinOtZP7UjZf/Tb2XnwZch9UUyp+hRnmNMO2fh3Fljf7Ym4A0vSDfHIL8mzNU0ppb5f1ErLzXCJnYGZuEVkbR8k1mN3VLUfGfeppzR9qSQNJgUPkgJbdJ1edZ506KzbWk7NaJqvHTrSuTC1pl2eXso3uwsxYWTufatlkjp+2P1mHX+j1zZxtO87hNTDr7QDCaAlZSe7kbTDZSdfu3OovfUE/Ajp1OHEcCWV/3OEmT4PQkskkW65MSJmcNxBQIQ/lti/J84swB/Ft3rPCqiKcbJo8ghm5NzBHRvdZYYVOCdlQJML9ei9r9D04x8OiChlhkRzG5RgpnzgvyTyyAubrIUiUY54lovw9EDrCosS7DhqUaXFam9IqHY6t0uHYKh2Ora5z+C8AAAD//xfzwlkAAAAGSURBVAMANhan0Wsb270AAAAASUVORK5CYII='
